[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cd frontend && npm install',
  'cd backend && npm install'
]

[phases.build]
cmds = [
  'cd frontend && npm run build'
]

[start]
cmd = 'cd backend && npm start'
